services:
  db:
    image: postgres:15-alpine
    networks:
      - wareflow_net
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-wareflow}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    networks:
      - wareflow_net
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - wareflow_net
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  wareflow_net:
    driver: bridge

volumes:
  postgres_data:
